// Generated by CoffeeScript 1.9.3
(function() {
  var Router, bodyParser, fs, parsers, path, router;

  bodyParser = require('body-parser');

  Router = require('express').Router;

  fs = require('fs');

  path = require('path');

  router = new Router();

  parsers = require('./parsers');

  router.use(bodyParser.json());

  router.use(bodyParser.urlencoded({
    extended: false
  }));

  router.use(function(req, res, next) {
    var i, len, parser;
    for (i = 0, len = parsers.length; i < len; i++) {
      parser = parsers[i];
      if (parser(req)) {
        return next();
      }
    }
    return next(new Error('parser not found'));
  });

  module.exports = router;

}).call(this);
