// Generated by CoffeeScript 1.9.3
(function() {
  var moment;

  moment = require('moment');

  module.exports = function(req) {
    var commit, data, i, len, ref, results;
    if (req.headers['user-agent'] !== 'Bitbucket.org') {
      return false;
    }
    if (!req.body.payload) {
      return false;
    }
    data = JSON.parse(req.body.payload);
    req.payload = {
      commits: []
    };
    if (data.commits) {
      ref = data.commits;
      results = [];
      for (i = 0, len = ref.length; i < len; i++) {
        commit = ref[i];
        results.push(req.payload.commits.push({
          hash: commit.raw_node,
          message: commit.message,
          date: moment(commit.utctimestamp).toISOString(),
          branch: commit.branch
        }));
      }
      return results;
    }
  };

  return true;

}).call(this);
