// Generated by CoffeeScript 1.9.3
(function() {
  var moment;

  moment = require('moment');

  module.exports = function(req) {
    var change, i, len, ref;
    if (req.headers['user-agent'] !== 'Bitbucket-Webhooks/2.0') {
      return false;
    }
    req.payload = {
      commits: []
    };
    if (req.body.push && req.body.push.changes) {
      ref = req.body.push.changes;
      for (i = 0, len = ref.length; i < len; i++) {
        change = ref[i];
        if (change["new"].target.type === 'commit' && change["new"].type === 'branch') {
          req.payload.commits.push({
            hash: change["new"].target.hash,
            message: change["new"].target.message,
            date: moment(change["new"].target.date).toISOString(),
            branch: change["new"].name
          });
        }
      }
    }
    return true;
  };

}).call(this);
